Add two stress tests and one problem test
IvanRenison/kactl pull request #17
Opened 2024-05-24 04:16 UTC by Aplietexe

2024-05-24 19:04 UTC, IvanRenison commented on content/graph/CompressTree.h
> + * every pair of vertices in which one is an ancestor of the other in $T$.
Volver a agregar que es el mínimo y cuantos se agregan como máximo

2024-05-24 19:06 UTC, IvanRenison commented on stress-tests/graph/CompressTree.cpp
> +	typedef vector<pair<ll, ll>> vii;
Podés usar:
`typedef vector<ii> vii;`

2024-05-24 19:09 UTC, IvanRenison requested changes

2024-05-24 19:09 UTC, IvanRenison commented on stress-tests/graph/CompressTree.cpp
> +			for (size_t j = i+1; j < subset.size(); ++j) {
¿Porque no usas fore?

2024-05-24 19:09 UTC, IvanRenison commented on test-problems/graph/BellmanFord.cpp
> +#define fore(i, a, b) for (ll i = a, gmat = b; assert(b == gmat), i < gmat; i++)
¿Porque ese assert?

2024-05-26 23:14 UTC, IvanRenison requested changes

2024-05-26 23:14 UTC, IvanRenison commented on content/graph/CompressTree.h
> + * tree with vertex set $\{\text{lca}(x,y):x\in X,y\in X\}$ and edges between
Agregar espacios en la fórmula latex: $\{\text{lca}(x,y) : x \in X, y \in X\}$
No cambia nada, pero para que sea mas legible en el código

2024-05-26 23:14 UTC, IvanRenison commented on stress-tests/graph/BinaryLifting.cpp
> +		vector<ll> depth(n, 0);
Usar `vi`

2024-05-26 23:14 UTC, IvanRenison commented on test-problems/graph/BellmanFord.cpp
> +	return 0;
El return creo que no hace falta, ¿o por ser un juez muy viejo si hace falta?

2024-05-26 23:49 UTC, Aplietexe commented on test-problems/graph/BellmanFord.cpp
> +	return 0;
Da AC sin.

2024-05-27 11:28 UTC, IvanRenison approved these changes

2024-05-27 11:29 UTC, merged