Change graphs macros
IvanRenison/kactl pull request #18
Opened 2024-05-24 04:51 UTC by Aplietexe

2024-05-27 18:08 UTC, IvanRenison requested changes

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/2sat.h
Quizas cambiar `gr.emplace_back();` por `gr.pb({});`?

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/BinaryLifting.h
> - * Status: Tested at Petrozavodsk, also stress-tested via LCA.cpp
Porque borraste el ` via LCA.cpp`?

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/EdgeColoring.h
> +	for (ii e : eds) ++cc[e.fst], ++cc[e.snd];
Acá se podría usar pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/GeneralMatching.h
> +		ll a = pa.fst, b = pa.snd, r = rand() % mod;
Acá se podría usar pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/MinCostMaxFlow.h
> +		ed[to].pb(edge{ to,from,SZ(ed[from])-1,0,-cost,0 });
Poner espacios después de cada `,` y eliminar los del comienzo y final

2024-05-27 18:08 UTC, IvanRenison commented on content/graph/PushRelabel.h
`vi ec;` en lugar de `vector<ll> ec;`

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/DirectedMST.cpp
>  		if(cnt == 0)    break;
Acá se podrían eliminar espacios antes del break

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/EdgeColoring.cpp
> +	for (ii e : ed) ++deg[e.fst], ++deg[e.snd];
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/EulerWalk.cpp
> +					allEds[ii(b, a)].pb(i);
`{a, b}` en lugar de `ii(a, b)` debería anda

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/HLD.cpp
> +			tree1[i.snd].pb(i.fst);
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/HLD.cpp
>  		}
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/LCA.cpp
> +			oldTree[i.snd].pb({i.fst, 1});
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/LCA.cpp
>  		vector<ll> par(n), depth(n);
`vi`

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/LinkCutTree.cpp
> +				ii ed = edges[r];
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/LinkCutTree.cpp
> +				for(auto &ed: edges) uf.join(ed.fst, ed.snd);
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/graph/maxflow.cpp
> +		fore(i,0,n) for(auto &e: origEk[i]) {
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/utilities/genGraph.h
> +		ed[pa.snd].pb(pa.fst);
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on stress-tests/utilities/genTree.h
> +		p.fst--, p.snd--;
Pattern matching

2024-05-27 18:08 UTC, IvanRenison commented on test-problems/graph/BiconnectedComponents.cpp
Tenés que re-submitearlo y actualizar el link

2024-05-27 18:08 UTC, IvanRenison commented on test-problems/graph/TreePathQueries.cpp
Tenés que re-submitearlo y actualizar el link

2024-05-28 02:24 UTC, Aplietexe commented on content/graph/BinaryLifting.h
> - * Status: Tested at Petrozavodsk, also stress-tested via LCA.cpp
Eso debería haber ido en el otro PR. Mejor dejarlo ahora igual.

2024-05-28 15:55 UTC, IvanRenison requested changes

2024-05-28 15:55 UTC, IvanRenison commented on content/graph/2sat.h
> +		gr.pb({});
Poner en la misma linea

2024-05-28 15:55 UTC, IvanRenison commented on content/graph/2sat.h
> +		gr[j].pb(f^1);
Poner en la misma linea

2024-05-28 15:55 UTC, IvanRenison commented on content/graph/BinaryLifting.h
> - * Status: Tested at Petrozavodsk, also stress-tested via LCA.cpp
Pero sigue estando testeado en LCA.cpp, ¿verdad?

2024-05-28 15:55 UTC, IvanRenison commented on content/graph/GeneralMatching.h
> +		ll a = u, b = v, r = rand() % mod;
Podes hacer `auto [a, b]` y eliminar las asignaciones

2024-05-28 15:55 UTC, IvanRenison commented on stress-tests/graph/HLD.cpp
> +			tree1[v].pb(u);
Poner en la misma linea

2024-05-28 15:55 UTC, IvanRenison commented on stress-tests/graph/HLD.cpp
> +			tree1[v].pb(u);
Poner en la misma linea

2024-05-28 15:55 UTC, IvanRenison commented on stress-tests/graph/LCA.cpp
> +			oldTree[v].pb({u, 1});
Unificar lineas

2024-05-28 15:55 UTC, IvanRenison commented on stress-tests/utilities/genGraph.h
> +		ed[v].pb(u);
Poner en la misma linea

2024-05-28 16:07 UTC, Aplietexe commented on content/graph/BinaryLifting.h
> - * Status: Tested at Petrozavodsk, also stress-tested via LCA.cpp
Pongo que está en ambos.

2024-05-28 17:40 UTC, IvanRenison approved these changes

2024-05-28 17:41 UTC, merged