Rerooting DP
IvanRenison/kactl pull request #25
Opened 2024-07-06 19:55 UTC by Aplietexe

2024-07-27 21:40 UTC, IvanRenison requested changes
Hacer código mas entendible

2024-08-08 18:58 UTC, IvanRenison requested changes
Agregar ejemplo de como sería calcular la dp normal con las operaciones

2024-08-13 22:47 UTC, IvanRenison requested changes
Considerar usar un struct

2024-08-21 18:22 UTC, IvanRenison commented on content/graph/Reroot.h
> +									root_dp(n),fdp(n),bdp(n) {}
```suggestion
	Reroot(vector<vi>& g, vd& neuts) : n(SZ(g)), g(g),
			neuts(neuts), root_dp(n), fdp(n), bdp(n) {}
```

2024-09-12 21:30 UTC, IvanRenison commented on content/graph/Reroot.h
> +		: n(SZ(g)), g(g), neuts(neuts), root_dp(n), fdp(n),bdp(n){}
```suggestion
	Reroot(vector<vi>& g, vd& neuts) : n(SZ(g)), g(g),
			neuts(neuts), root_dp(n), fdp(n), bdp(n) {}
```

2024-09-12 21:31 UTC, IvanRenison commented on content/graph/Reroot.h
> +		vd dp = neuts, e(n); vi o, p(n); o.reserve(n), o.pb(0);
```suggestion
		vd dp = neuts, e(n); vi o = {0}, p(n); o.reserve(n);
```

2024-09-12 21:33 UTC, IvanRenison commented on content/graph/Reroot.h
> +			else acc(dp[u], dp[g[u][ei]], u, ei);
```suggestion
			fore(ei, 0, SZ(g[u]))
				if (g[u][ei] == p[u]) pei = ei;
				else acc(dp[u], dp[g[u][ei]], u, ei);
```

2024-09-12 21:38 UTC, IvanRenison commented on content/graph/Reroot.h
> +		for (ll b = bit_width((unsigned)d) - 1; b >= 0; b--) {
```suggestion
		for (ll b = bit_width((unsigned)d); b--;) {
```

2024-09-12 21:39 UTC, IvanRenison commented on content/graph/Reroot.h
> +			for (ll i = d - 1; i >= 0; i--)
```suggestion
		for (ll b = bit_width((unsigned)d); b--;) {
			for (ll i = d; i--;)
```

2024-09-12 21:42 UTC, IvanRenison commented on content/graph/Reroot.h
> +		p_ans = Data{};
```suggestion
		p_ans = {};
```
¿Algo así no anda? (En los otros archivos también aplica esta sugerencia)

2024-09-12 21:43 UTC, IvanRenison commented on content/graph/RerootLinear.h
> +		for(ll i=d-1;i>=0;i--) s[i] = merge(a[i], s[i + 1], v);
```suggestion
		for(ll i = d; i--;) s[i] = merge(a[i], s[i + 1], v);
```

2024-09-12 22:10 UTC, IvanRenison commented on content/graph/Reroot.h
> + * \ \ \texttt{return dp[u] = finalize(res, u, pid);}
Acá no queda claro que con la raíz se llama a finalize con -1

2024-09-12 22:12 UTC, IvanRenison commented on content/graph/Reroot.h
> + * \texttt{acc} according to the definitions below, adding any
```suggestion
 * Description: define \texttt{Data}, \texttt{finalize},
 * \texttt{acc} (as explained below), adding any
```

2024-09-12 22:13 UTC, IvanRenison commented on content/graph/Reroot.h
> + * \texttt{g[v][ei]} is the root.
```suggestion
 * \texttt{root\_dp[v]} is the answer for the whole tree with
 * \texttt{v} as root, \texttt{fdp[v][ei]} is the answer for
 * \texttt{g[v][ei]} if \texttt{v} is the root and
 * \texttt{bdp[v][ei]} is the answer for \texttt{v} if
 * \texttt{g[v][ei]} is the root.
```

2024-09-12 22:15 UTC, IvanRenison requested changes
Comentarios

2024-09-12 23:27 UTC, Aplietexe commented on content/graph/Reroot.h
> +		p_ans = Data{};
Sí anda creo. Es por claridad nomás. Eso no se copia realmente sino que lo vas a definir según el problema.

2024-09-13 12:01 UTC, IvanRenison commented on stress-tests/graph/Reroot.cpp
> +	};
Este código y el de la descripción estaría bueno que sean el mismo

2024-10-07 22:45 UTC, IvanRenison requested changes

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/RerootInv.h
> +#include "Reroot.h"
```suggestion
#pragma once

#include "Reroot.h"
```

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/RerootLinear.h
> +		for(ll i = d; i--;) s[i] = merge(a[i], s[i + 1], v);
```suggestion
		for (ll i = d; i--;) s[i] = merge(a[i], s[i + 1], v);
```
Esto igual porque está así en el resto de este código, pero en todo el kactl está de las dos formas

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/Reroot.h
> +	vd& neuts;
```suggestion
	ll n; vector<vi>& g; vd& neuts;
```

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/Reroot.h
> +	vector<vd> fdp, bdp;
```suggestion
	vd root_dp; vector<vd> fdp, bdp;
```

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/RerootInv.h
> +		Data b = ne;
```suggestion
		ll d = SZ(a); Data b = ne;
```

2024-10-07 22:45 UTC, IvanRenison commented on content/graph/RerootLinear.h
> +		vd p(d + 1, ne), s(d + 1, ne);
```suggestion
		ll d = SZ(a); vd p(d + 1, ne), s(d + 1, ne);
```

2024-10-08 14:09 UTC, IvanRenison requested changes

2024-10-08 14:09 UTC, IvanRenison commented on content/graph/RerootLinear.h
> +#include "Reroot.h"
```suggestion
#pragma once

#include "Reroot.h"
```

2024-10-08 15:49 UTC, IvanRenison approved these changes

2024-10-08 15:49 UTC, merged