Change various macros
IvanRenison/kactl pull request #34
Opened 2024-08-08 01:27 UTC by Aplietexe

2024-08-08 15:50 UTC, IvanRenison commented on content/various/DivideAndConquerDP.h
>  	void solve(ll L, ll R) { rec(L, R, INT_MIN, INT_MAX); }
Esto quedó mal del cambio de int a ll, cambiar a `LLONG_MIN` y `LLONG_MAX`

2024-08-08 15:52 UTC, IvanRenison commented on content/various/IntervalCover.h
>  		pair<T, ll> mx = make_pair(cur, -1);
¿Esto no se puede hacer mas corto?

2024-08-08 16:15 UTC, Aplietexe commented on content/various/DivideAndConquerDP.h
>  	void solve(ll L, ll R) { rec(L, R, INT_MIN, INT_MAX); }
Está mal en otro lugares también. Lo arreglo en #37.

2024-08-08 16:56 UTC, IvanRenison requested changes
merge gmat para arreglar los conflictos

2024-08-09 11:41 UTC, IvanRenison approved these changes

2024-08-09 11:42 UTC, merged