Add Diophantine.h and tests
IvanRenison/kactl pull request #66
Opened 2024-10-12 00:24 UTC by Aplietexe

2024-10-13 12:27 UTC, IvanRenison requested changes

2024-10-13 12:27 UTC, IvanRenison commented on content/number-theory/Diophantine.h
> + * Source: vasito
```suggestion
 * Source: notebook el vasito
```
Así está puesto en el resto de los que vienen de el vasito

2024-10-13 12:27 UTC, IvanRenison commented on content/number-theory/Diophantine.h
> + * the form $(x + k \cdot dx, y + k \cdot dy)$ for integer $k$.
No entiendo eso de "are of the form", ¿qué cosa tienen que tener esa forma?

2024-10-13 12:28 UTC, IvanRenison commented on content/number-theory/Diophantine.h
> + * Author: Unknown
Yo siempre me pongo yo como autor cuando soy yo el que agrega algo de el vasito

2024-10-14 12:15 UTC, IvanRenison requested changes

2024-10-14 12:15 UTC, IvanRenison commented on content/number-theory/Diophantine.h
> + * Description: Returns $(x_0, y_0, dx, dy)$ such that all integer solutions (x, y) to $ax + by = r$
```suggestion
 * Description: Returns $(x_0, y_0, dx, dy)$ such that all integer solutions $(x, y)$ to $ax + by = r$
```
También es medio raro que en una parte el producto este con un puntito y en otra no

2024-10-15 00:39 UTC, Aplietexe commented on content/number-theory/Diophantine.h
> + * Description: Returns $(x_0, y_0, dx, dy)$ such that all integer solutions (x, y) to $ax + by = r$
Es solo porque ahí todas las variables son de una letra. dx y dy son de dos.

2024-10-15 12:31 UTC, IvanRenison approved these changes

2024-10-15 12:31 UTC, merged