Shorten SegmentTree2d
IvanRenison/kactl pull request #87
Opened 2024-10-29 14:37 UTC by IvanRenison

2024-10-29 14:55 UTC, Aplietexe requested changes

2024-10-29 14:55 UTC, Aplietexe commented on content/data-structures/SegmentTree2d.h
>  			ll t[4], q = 0;
Por ahí conviene usar `array<ll, 4>`?

2024-10-29 15:05 UTC, IvanRenison commented on content/data-structures/SegmentTree2d.h
>  			ll t[4], q = 0;
Tenía dudas de si hacerlo. Como está ahora es mas corto de copiar, y justo en este caso parece muy poco probable que tengamos que interactuar o debuguear con esa variable

2024-10-30 19:31 UTC, Aplietexe approved these changes

2024-10-30 19:31 UTC, merged