Add PointsUnderLine
IvanRenison/kactl pull request #99
Opened 2024-11-05 06:39 UTC by Aplietexe

2024-11-05 12:32 UTC, IvanRenison requested changes
Hay que agregarlo al PDF
Y otra cosa, ¿no iría en geometría?

2024-11-05 16:38 UTC, Aplietexe commented
> Hay que agregarlo al PDF Y otra cosa, ¿no iría en geometría?

La parte de lattices suele tener mucho más que ver con teoría de números, divisibilidad y para derivar esas fórmulas se usan cosas de teoría de números. No tiene mucho que ver con la geometría "continua".

2024-11-05 22:21 UTC, IvanRenison requested changes

2024-11-05 22:21 UTC, IvanRenison commented on content/number-theory/PointsUnderLine.h
> +	ll k = (a - 1) / b, h = (c - a * m) / b;
```suggestion
	ll m = c / a, k = (a - 1) / b, h = (c - a * m) / b;
	if (a == b) return m * (m - 1) / 2;
```

2024-11-06 15:29 UTC, IvanRenison approved these changes

2024-11-06 15:30 UTC, merged